### ISSUE TITLE
[feature request] being able to detect all test modules

### ISSUE THREAD

**Issue by sequencer** [lefou/mill-jacoco#3]
These two lines indicate `mill-jacoco` only support test package in `test` name:
https://github.com/lefou/mill-jacoco/blob/6e494eff58464e506e789acb9891b51f22b89f68/core/src/de/tobiasroeser/mill/jacoco/JacocoReportModule.scala#L58-L59

for other packages `foo extends Tests` or `bar extends Tests` cannot be detected by Jacobo.
a cursed idea is finding a directory having `testFramework`(or some internal test api) to automatically detect the test packages

**Comment by lefou** [comment]
It's not clear to me what you want to achieve. The basic idea behind these parameters was to have a simple way to select sources. Because of the way how Mill works, a `__.allSources` also includes tests, which we then exclude.

Do you want to exclude Mill modules/targets or do you want to inspect arbitrary Java source file whether they implement some kind of test framework? I'm assuming the former.

If you only want to catch more test modules (e.g. when you have test projects, that have other names), it's probably easier to just inspect all modules and detect tests by the fact that they implement `trait TestModule`.

It would be nice, if Mill had some way to select modules by type. E.g `_:TestModule`

**Comment by lefou** [comment]
I just opened a PR in Mill that added type filters: https://github.com/com-lihaoyi/mill/pull/2997

After it is merged, we should be able to express exactly the right sources:

```
__:JavaModule:!TestModule.sources
```
